#**Making Training Data:**

In [1]:
import numpy as np
import torch

In [2]:
# Input ---> (temp, rainfall, humidity) ---> yield of apple and oranges crops
inputs = np.array([
    [73, 67,43],
    [91, 88, 64],
    [87, 134, 58],
    [102, 43, 37],
    [69, 96, 70],
], dtype = 'float32')

In [ ]:
target = np.array([
    [56, 70],
    [81, 101],
    [119, 113],
    [22, 37],
    [103, 119]
], dtype = 'float32')

In [3]:
# Target (apples, oranges)

target = np.array([
    [56, 70],
    [81, 101],
    [119, 113],
    [22, 37],
    [103, 119]
], dtype = 'float32')

#**These are numpy arrays. Dataset will normally consist of numpy arrays but our model will always be trained on tensors**

In [4]:
# convert inputs and target to tensors

inputs = torch.from_numpy(inputs)
target = torch.from_numpy(target)

print(inputs)
print(target)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 113.],
        [ 22.,  37.],
        [103., 119.]])


# **Weights and Biases:**

In [8]:
w = torch.randn(2,3,requires_grad = True)
b = torch.randn(2, requires_grad = True)

# Why true? - So that we can use autograd

print(w)
print(b)

tensor([[-2.7890,  0.7834,  2.4460],
        [-0.3002, -0.4856,  0.9996]], requires_grad=True)
tensor([-0.2308,  1.1176], requires_grad=True)


# **Defining the Model:**

In [9]:
# Z = X * W + B
def model(x):
  return x @ w.t() + b # w.t() - Transpose of weights

# **Prediction:**

In [11]:
preds = model(inputs)
print(preds)

tensor([[ -46.1650,  -10.3442],
        [ -28.5505,   -4.9526],
        [   3.9661,  -32.0847],
        [-160.5244,  -13.3928],
        [  53.7513,    3.7638]], grad_fn=<AddBackward0>)


# **Loss Function: MSE -> Mean squared error:**

In [17]:
def MSE(y,y_hat):
  diff = y - y_hat
  return torch.sum(diff * diff) / diff.numel()


# Error
loss = MSE(target,preds)
print(loss)

tensor(12596.1895, grad_fn=<DivBackward0>)


# **Computing Gradients:**

In [18]:
loss.backward()

In [19]:
print(w)
print(w.grad)

tensor([[-2.7890,  0.7834,  2.4460],
        [-0.3002, -0.4856,  0.9996]], requires_grad=True)
tensor([[-9890.1484, -8895.2949, -5655.4219],
        [-8244.1084, -9475.5605, -5716.3486]])


In [20]:
print(b)
print(b.grad)

tensor([-0.2308,  1.1176], requires_grad=True)
tensor([-111.7045,  -99.4021])


In [21]:
#reset grad
w.grad.zero_()
b.grad.zero_()

print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


# **Adjusting parameters:**

In [22]:
preds = model(inputs)
print(preds)

loss = MSE(target,preds)
print(loss)

tensor([[ -46.1650,  -10.3442],
        [ -28.5505,   -4.9526],
        [   3.9661,  -32.0847],
        [-160.5244,  -13.3928],
        [  53.7513,    3.7638]], grad_fn=<AddBackward0>)
tensor(12596.1895, grad_fn=<DivBackward0>)


In [23]:
loss.backward()

print(w.grad)
print(b.grad)

tensor([[-9890.1484, -8895.2949, -5655.4219],
        [-8244.1084, -9475.5605, -5716.3486]])
tensor([-111.7045,  -99.4021])


In [24]:
# Adjusting weight and reset grad

learning_rate = 1e-5

with torch.no_grad():
  w-= w.grad * 1e-5
  b-= b.grad * 1e-5

  w.grad.zero_()
  b.grad.zero_()

In [25]:
print(w)
print(b)

tensor([[-2.6901,  0.8724,  2.5025],
        [-0.2177, -0.3908,  1.0567]], requires_grad=True)
tensor([-0.2297,  1.1186], requires_grad=True)


In [26]:
# Claculating again

preds = model(inputs)
loss = MSE(target,preds)
print(loss)

tensor(8958.6299, grad_fn=<DivBackward0>)


# **Training for multiple Epochs:**

In [27]:
for i in range(400):
  preds = model(inputs)
  loss = MSE(target, preds)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

    w.grad.zero_()
    b.grad.zero_()
  print(f"Epochs({i}/{100}) & Loss {loss}")

Epochs(0/100) & Loss 8958.6298828125
Epochs(1/100) & Loss 6502.1435546875
Epochs(2/100) & Loss 4841.63134765625
Epochs(3/100) & Loss 3717.57958984375
Epochs(4/100) & Loss 2955.099365234375
Epochs(5/100) & Loss 2436.341552734375
Epochs(6/100) & Loss 2081.88427734375
Epochs(7/100) & Loss 1838.2080078125
Epochs(8/100) & Loss 1669.2435302734375
Epochs(9/100) & Loss 1550.68603515625
Epochs(10/100) & Loss 1466.154296875
Epochs(11/100) & Loss 1404.609619140625
Epochs(12/100) & Loss 1358.612060546875
Epochs(13/100) & Loss 1323.146728515625
Epochs(14/100) & Loss 1294.834716796875
Epochs(15/100) & Loss 1271.3968505859375
Epochs(16/100) & Loss 1251.29833984375
Epochs(17/100) & Loss 1233.5018310546875
Epochs(18/100) & Loss 1217.31005859375
Epochs(19/100) & Loss 1202.250732421875
Epochs(20/100) & Loss 1188.005859375
Epochs(21/100) & Loss 1174.3603515625
Epochs(22/100) & Loss 1161.1678466796875
Epochs(23/100) & Loss 1148.3304443359375
Epochs(24/100) & Loss 1135.780517578125
Epochs(25/100) & Loss 112

In [28]:
preds = model(inputs)
loss = MSE(target, preds)
print(loss)

tensor(110.4128, grad_fn=<DivBackward0>)


In [29]:
from math import sqrt
sqrt(loss)

/tmp/ipython-input-3167310485.py:2: UserWarning: Converting a tensor with requires_grad=True to a scalar may lead to unexpected behavior.
Consider using tensor.detach() first. (Triggered internally at /pytorch/torch/csrc/autograd/generated/python_variable_methods.cpp:836.)
  sqrt(loss)


10.50774933182686

In [30]:
preds

tensor([[ 54.7659,  67.7452],
        [ 91.3653, 100.4515],
        [101.7205, 112.8314],
        [  8.4357,  40.8221],
        [125.1894, 118.5492]], grad_fn=<AddBackward0>)

In [31]:
target

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 113.],
        [ 22.,  37.],
        [103., 119.]])